#!/usr/bin/env php
<?php

/*
    lineDUBbed LDC installer

    Copyright:  Copyright (c) 2023 Elias Batek
    License:    $(HTTP www.boost.org/LICENSE_1_0.txt, Boost License 1.0).
    Authors:    Elias Batek
 */

declare(strict_types=1);

require __DIR__ . '/installer.inc.php';
$status = main('ldc', $argc, $argv);
exit($status);
